# Sensible prefix
unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix
# Make sure vim and friends work as expected
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Sane window split commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g window-status-separator ''

# Switch panes using vim keys
bind h  select-pane -L
bind l select-pane -R
bind k  select-pane -U
bind j select-pane -D

# Allow for faster key repition
set -s escape-time 0

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# customize split colors
set -g pane-border-style fg=colour235,bg="#000000"
set -g pane-active-border-style fg=colour57,bg="#000000"

# set message bar to follow colour scheme
set-option -g message-command-style fg=colour57,bg="#000000"
set-option -g message-style fg=colour57,bright,bg="#000000"

# Nerd font
# 
set -g status-position bottom
set -g status-bg "#000000"
set -g status-left ''
set -g status-right ''
set -g status-justify centre

setw -g mode-keys vi

# Tabs look nice
setw -g window-status-format ' #[fg=colour235]#[bg=colour235, fg=colour233]#I #W #[fg=colour235, bg=colour233]'
setw -g window-status-current-format ' #[fg=colour57]#[bg=colour57, fg=colour233]#I #W #[fg=colour57, bg=colour233]'


set-option -g history-limit 5000
